* K-Fold Cross Validation
* Repeated K-Fold Cross Validation
* Leave One Out
* Leave P Out
* Stratified K-Fold Cross Validation

In [4]:
import pandas as pd
import numpy as np
from scipy.special import comb
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [3]:
from sklearn.model_selection import KFold, RepeatedKFold, LeaveOneOut, LeavePOut, StratifiedKFold, cross_validate

In [5]:
breast_cancer_X, breast_cancer_y = load_breast_cancer(return_X_y=True)

In [6]:
X = pd.DataFrame(breast_cancer_X)
y = pd.Series(breast_cancer_y).map({0:1, 1:0})

In [7]:
X.head(5)

0      1       2       3        4        5       6        7       8   \
0  17.99  10.38  122.80  1001.0  0.11840  0.27760  0.3001  0.14710  0.2419   
1  20.57  17.77  132.90  1326.0  0.08474  0.07864  0.0869  0.07017  0.1812   
2  19.69  21.25  130.00  1203.0  0.10960  0.15990  0.1974  0.12790  0.2069   
3  11.42  20.38   77.58   386.1  0.14250  0.28390  0.2414  0.10520  0.2597   
4  20.29  14.34  135.10  1297.0  0.10030  0.13280  0.1980  0.10430  0.1809   

        9   ...     20     21      22      23      24      25      26      27  \
0  0.07871  ...  25.38  17.33  184.60  2019.0  0.1622  0.6656  0.7119  0.2654   
1  0.05667  ...  24.99  23.41  158.80  1956.0  0.1238  0.1866  0.2416  0.1860   
2  0.05999  ...  23.57  25.53  152.50  1709.0  0.1444  0.4245  0.4504  0.2430   
3  0.09744  ...  14.91  26.50   98.87   567.7  0.2098  0.8663  0.6869  0.2575   
4  0.05883  ...  22.54  16.67  152.20  1575.0  0.1374  0.2050  0.4000  0.1625   

       28       29  
0  0.4601  0.11890  
1  0.2750  0.08902  
2  0.3613  0.08758  
3  0.6638  0.17300  
4  0.2364  0.07678  

[5 rows x 30 columns]

In [8]:
X.tail(4)

0      1       2       3        4        5        6        7       8   \
565  20.13  28.25  131.20  1261.0  0.09780  0.10340  0.14400  0.09791  0.1752   
566  16.60  28.08  108.30   858.1  0.08455  0.10230  0.09251  0.05302  0.1590   
567  20.60  29.33  140.10  1265.0  0.11780  0.27700  0.35140  0.15200  0.2397   
568   7.76  24.54   47.92   181.0  0.05263  0.04362  0.00000  0.00000  0.1587   

          9   ...      20     21      22      23       24       25      26  \
565  0.05533  ...  23.690  38.25  155.00  1731.0  0.11660  0.19220  0.3215   
566  0.05648  ...  18.980  34.12  126.70  1124.0  0.11390  0.30940  0.3403   
567  0.07016  ...  25.740  39.42  184.60  1821.0  0.16500  0.86810  0.9387   
568  0.05884  ...   9.456  30.37   59.16   268.6  0.08996  0.06444  0.0000   

         27      28       29  
565  0.1628  0.2572  0.06637  
566  0.1418  0.2218  0.07820  
567  0.2650  0.4087  0.12400  
568  0.0000  0.2871  0.07039  

[4 rows x 30 columns]

In [9]:
y.value_counts() / len(y)

0    0.627417
1    0.372583
dtype: float64

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [11]:
X_train.shape

(398, 30)

In [12]:
X_test.shape

(171, 30)

K-Fold Cross Validation

In [14]:
logit = LogisticRegression(penalty = 'l2', C = 10, solver = 'liblinear', random_state = 4, max_iter = 10000)


kf = KFold(n_splits = 5, shuffle= True, random_state = 4)

clf = cross_validate(logit, X_train, y_train, scoring = 'accuracy', return_train_score = True, cv = kf)

clf['test_score']

array([0.925     , 0.95      , 0.9625    , 0.96202532, 0.94936709])

In [15]:
clf['train_score']

array([0.97169811, 0.96540881, 0.96855346, 0.96238245, 0.97178683])

In [16]:
print('mean train set accuracy: ', np.mean(clf['train_score']), ' +- ', np.std(clf['train_score']))
print('mean test set accuracy: ', np.mean(clf['test_score']), ' +- ', np.std(clf['test_score']))

mean train set accuracy:  0.9679659312710711  +-  0.003649325403713798
mean test set accuracy:  0.9497784810126582  +-  0.013608919570498668


Repeated K-Fold Cross Validation

In [17]:
logit = LogisticRegression(penalty ='l2', C = 1, solver = 'liblinear', random_state = 4, max_iter = 10000)

rkf = RepeatedKFold(n_splits = 5, n_repeats = 10, random_state=4)

print('We expect K * n performance metrics: ', 5*10)

clf =  cross_validate(logit, X_train, y_train, scoring = 'accuracy', return_train_score = True, cv = rkf)

print('Number of metrics obtained: ', len(clf['test_score']))

clf['test_score']

We expect K * n performance metrics:  50
Number of metrics obtained:  50


array([0.9       , 0.9375    , 0.975     , 0.96202532, 0.94936709,
       0.9625    , 0.9625    , 0.9125    , 0.96202532, 0.92405063,
       0.9875    , 0.95      , 0.975     , 0.91139241, 0.96202532,
       0.95      , 0.95      , 0.95      , 0.92405063, 0.96202532,
       0.975     , 0.9125    , 0.9375    , 0.94936709, 0.96202532,
       0.9875    , 0.9125    , 0.9375    , 0.91139241, 0.96202532,
       0.9625    , 0.9375    , 0.95      , 0.92405063, 0.93670886,
       0.95      , 0.95      , 0.95      , 0.98734177, 0.88607595,
       0.95      , 0.925     , 0.9625    , 0.96202532, 0.94936709,
       0.925     , 0.9625    , 0.925     , 0.91139241, 0.96202532])

In [18]:
print('mean train set accuracy: ', np.mean(clf['train_score']), ' +- ', np.std(clf['train_score']))
print('mean test set accuracy: ', np.mean(clf['test_score']), ' +- ', np.std(clf['test_score']))

mean train set accuracy:  0.9600485006210445  +-  0.006385366206243238
mean test set accuracy:  0.9457151898734176  +-  0.0232708755411947


Leave One Out

In [19]:
logit = LogisticRegression(penalty = 'l2', C = 1, solver = 'liblinear', random_state = 4, max_iter = 10000)

leave_one_out = LeaveOneOut()

print('We expect as many metrics as data in the train set: ', len(X_train))

clf =  cross_validate(logit, X_train, y_train, scoring = 'accuracy', return_train_score = True, cv = leave_one_out)

print('Number of metrics obtained: ', len(clf['test_score']))

len(clf['test_score'])

We expect as many metrics as data in the train set:  398
Number of metrics obtained:  398


398

In [20]:
print('mean train set accuracy: ', np.mean(clf['train_score']), ' +- ', np.std(clf['train_score']))
print('mean test set accuracy: ', np.mean(clf['test_score']), ' +- ', np.std(clf['test_score']))

mean train set accuracy:  0.9575016138627649  +-  0.001227165161341965
mean test set accuracy:  0.9447236180904522  +-  0.22851893469149895


Leave P Out

In [21]:
logit = LogisticRegression(penalty = 'l2', C = 1, solver = 'liblinear', random_state = 4, max_iter = 10000)

leave_p_out = LeavePOut(p=2)

X_train_small = X_train.head(100)
y_train_small = y_train.head(100)

print('We expect : ', comb(100,2), ' metrics')


clf = cross_validate(logit, X_train_small, y_train_small, scoring = 'accuracy', return_train_score = True,cv = leave_p_out)

print('Number of metrics obtained: ', len(clf['test_score']))

We expect :  4950.0  metrics
Number of metrics obtained:  4950


In [22]:
print('mean train set accuracy: ', np.mean(clf['train_score']), ' +- ', np.std(clf['train_score']))
print('mean test set accuracy: ', np.mean(clf['test_score']), ' +- ', np.std(clf['test_score']))

mean train set accuracy:  0.9700020614306328  +-  0.0032367717044687024
mean test set accuracy:  0.9187878787878788  +-  0.19324591925218415


Stratified K-Fold Cross Validation

In [23]:
logit = LogisticRegression(penalty = 'l2', C = 1, solver = 'liblinear', random_state = 4, max_iter = 10000)

stratified_kf = StratifiedKFold(n_splits = 5, shuffle = True, random_state = 4)

clf =  cross_validate(logit, X_train, y_train,scoring = 'accuracy', return_train_score = True,cv =stratified_kf)

len(clf['test_score'])

5

In [24]:
print('mean train set accuracy: ', np.mean(clf['train_score']), ' +- ', np.std(clf['train_score']))
print('mean test set accuracy: ', np.mean(clf['test_score']), ' +- ', np.std(clf['test_score']))

mean train set accuracy:  0.9585495283018869  +-  0.00979089262321072
mean test set accuracy:  0.9422435897435898  +-  0.023106640409895497
