###  Numpy exercises

* Extracting all odd number from and array


* Reshaping and array


* Stacking two arrays vertically & horizontally


* Extracting common items from two arrays 


* Getting numbers between a given range of a numpy array

In [1]:
import numpy as np

In [2]:
first_array = np.arange(20)

In [3]:
odd_array = first_array[first_array%2 !=0]

In [4]:
odd_array

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [5]:
first_array.reshape(2, -1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [6]:
# Stacking 

array_1 = np.arange(10).reshape(2, -1)

array_2 = np.repeat(1, 10).reshape(2, -1)

In [7]:
array_1


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [8]:
array_2

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [9]:
np.vstack((array_1, array_2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
np.hstack((array_1, array_2))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [11]:
array_3 = np.array([1, 2, 3, 4, 5, 7, 8, 99, 101])
array_4 = np.array([1, 7, 77, 11, 12, 88, 97, 4, 101])

In [12]:
print(np.unique(array_3[array_3 == array_4]))

[  1 101]


In [13]:
array_5 = np.array([1, 3, 5, 77, 8, 23, 52, 37, 81, 49])

In [14]:
array_5[(array_5 > 6) & (array_5 < 55)]

array([ 8, 23, 52, 37, 49])