### Numpy exercises


* Swapping columns in an array


* Reversing the rows and columns of an array

In [1]:
import numpy as np

In [2]:
array_1 = np.arange(9).reshape(3,3)
array_2 = np.arange(9).reshape(3,3)
array_3 = np.arange(9).reshape(3,3)


array_1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
temp_array = array_1[:,0].copy() 

array_1[:,0], array_1[:,1] = array_1[:,1], temp_array

array_1

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [4]:
array_2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
# Reversing rows

array_2[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [6]:
array_3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
# Reversing columns

array_3[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])